//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Attacks
{
	public class DownBoy : StellarDrive
	{
		public DownBoy ()
		{
			frames = 100;

			commands.Add ("236236C");
			commands.Add ("236236D");
			commands.Add ("214214C");
			commands.Add ("214214D");
		}

		override protected void attack (PlayerController player, PlayerController enemy)
		{
			if( frames % 10 == 0 )
			{
				//flipDamage is used here so the target is bounced back and forth
				//within the whip zone
				if( player.flipDamage == false )
				{
					enemy.amIgettingHitDownBoy( 200, 0, 20, 2 );
					player.flipDamage = true;
				}
				else
				{
					enemy.amIgettingHitDownBoy( -200, 0, 20, 2 );
					player.flipDamage = false;
				}
			}
		}
	}
}

