//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Attacks
{
	public abstract class StellarDrive
	{
		protected int frames;
		protected bool isAttacking = false;

		public void attemptAttack (int currentFrames, PlayerController player, PlayerController enemy)
		{
			if (!isAttacking && canAttack (currentFrames))
			{
				isAttacking = true;
				PlaySound();
			}
			if (isAttacking)
			{
				attack (player, enemy);

				if (endAttack (currentFrames))
					isAttacking = false;
			}
		}
		
		protected bool canAttack (int currentFrames)
		{
			return currentFrames >= frames;
		}
		
		protected bool endAttack (int currentFrames)
		{
			return currentFrames == 0;
		}

		void PlaySound ()
		{

		}

		void attack (PlayerController player, PlayerController enemy);
	}
}